In [6]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [2]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}03-01-2020.csv", encoding="utf-8-sig")
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140

In [12]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

try :
    doc = doc[["Province_State", "Country_Region", "Confirmed"]]
except :
    doc = doc[["Province/State", "Country/Region", "Confirmed"]]
    doc.columns = ["Province_State", "Country_Region", "Confirmed"]

doc = doc.dropna(subset=["Confirmed"])
doc = doc.astype({"Confirmed": "int64"})

doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China          1
1        Beijing  Mainland China         14
2      Chongqing  Mainland China          6
3         Fujian  Mainland China          1
5      Guangdong  Mainland China         26

In [4]:
doc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66 entries, 0 to 75
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province_State  54 non-null     object
 1   Country_Region  66 non-null     object
 2   Confirmed       66 non-null     int64
dtypes: int64(1), object(2)
memory usage: 2.1+ KB

In [5]:
country_info = pd.read_csv("./COVID-19-master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv")

country_info.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Population
0,4,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.93911,67.709953,Afghanistan,38928341.0
1,8,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.15330,20.168300,Albania,2877800.0
2,10,AQ,ATA,10.0,NaN,NaN,NaN,Antarctica,-71.94990,23.347000,Antarctica,NaN
3,12,DZ,DZA,12.0,NaN,NaN,NaN,Algeria,28.03390,1.659600,Algeria,43851043.0
4,20,AD,AND,20.0,NaN,NaN,NaN,Andorra,42.50630,1.521800,Andorra,77265.0

In [13]:
import pandas as pd

test_df = pd.merge(doc, country_info, on="Country_Region", how="left")

In [14]:
test_df.head()

,Province_State_x,Country_Region,Confirmed,UID,iso2,iso3,code3,FIPS,Admin2,Province_State_y,Lat,Long_,Combined_Key,Population
0,Anhui,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,Mainland China,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chongqing,Mainland China,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Guangdong,Mainland China,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3993 entries, 0 to 3992
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Province_State_x  3932 non-null   object
 1   Country_Region    3993 non-null   object
 2   Confirmed         3993 non-null   int64
 3   UID               3967 non-null   float64
 4   iso2              3965 non-null   object
 5   iso3              3965 non-null   object
 6   code3             3965 non-null   float64
 7   FIPS              3384 non-null   float64
 8   Admin2            3343 non-null   object
 9   Province_State_y  3927 non-null   object
 10  Lat               3820 non-null   float64
 11  Long_             3820 non-null   float64
 12  Combined_Key      3967 non-null   object
 13  Population        3817 non-null   float64
dtypes: float64(6), int64(1), object(7)
memory usage: 436.9+ KB

In [16]:
test_df.isnull().sum()

Province_State_x     61
Country_Region        0
Confirmed             0
UID                  26
iso2                 28
iso3                 28
code3                28
FIPS                609
Admin2              650
Province_State_y     66
Lat                 173
Long_               173
Combined_Key         26
Population          176
dtype: int64

In [20]:
nan_rows = test_df[test_df["iso2"].isnull()]
nan_rows

,Province_State_x,Country_Region,Confirmed,UID,iso2,iso3,code3,FIPS,Admin2,Province_State_y,Lat,Long_,Combined_Key,Population
0,Anhui,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,Mainland China,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chongqing,Mainland China,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Guangdong,Mainland China,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Guangxi,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Guizhou,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Hainan,Mainland China,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Hebei,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Henan,Mainland China,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Hubei,Mainland China,444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Hunan,Mainland China,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Jiangsu,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Jiangxi,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Liaoning,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Macau,Macau,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Ningxia,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Shandong,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Shanghai,Mainland China,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Shanxi,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Sichuan,Mainland China,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Taiwan,Taiwan,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Tianjin,Mainland China,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3429,Yunnan,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3430,Zhejiang,Mainland China,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3482,NaN,South Korea,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3488,NaN,Summer Olympics 2020,0,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,35.6491,139.7737,Summer Olympics 2020,NaN
3796,NaN,Winter Olympics 2022,0,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,39.9042,116.4074,Winter Olympics 2022,NaN

In [21]:
import json

with open("./COVID-19-master/csse_covid_19_data/country_convert.json", "r", encoding="utf-8-sig") as json_file :
    json_data = json.load(json_file)

In [23]:
print(json_data.keys())

dict_keys(['Mainland China', 'Macau', 'South Korea', 'Aruba', ' Azerbaijan', 'Bahamas, The', 'Cape Verde', 'Cayman Islands', 'Channel Islands', 'Curacao', 'Czech Republic', 'East Timor', 'Faroe Islands', 'French Guiana', 'Gambia, The', 'Gibraltar', 'Greenland', 'Guadeloupe', 'Guam', 'Guernsey', 'Hong Kong', 'Hong Kong SAR', 'Iran (Islamic Republic of)', 'Ivory Coast', 'Jersey', 'Macao SAR', 'Martinique', 'Mayotte', 'North Ireland', 'Palestine', 'Puerto Rico', 'Republic of Ireland', 'Republic of Korea', 'Republic of Moldova', 'Republic of the Congo', 'Reunion', 'Russian Federation', 'Saint Barthelemy', 'Saint Martin', 'St. Martin', 'Taipei and environs', 'The Bahamas', 'The Gambia', 'UK', 'Vatican City', 'Viet Nam', 'occupied Palestinian territory', 'Taiwan*', 'Malawi', 'South Sudan', 'Western Sahara', 'Namibia'])

In [24]:
# apply() : 특정 컬럼 내 각 행을 순회하면서 어떤 결과값을 적용하고자 할 때 사용!!

df = pd.DataFrame({
    "영어": [60, 70],
    "수학": [100, 50]
}, index = ["Dave", "David"])

df

       영어   수학
Dave   60  100
David  70   50

In [25]:
def func(df_data) :
    print(type(df_data))
    print(df_data.index)
    print(df_data.values)
    return df_data

In [26]:
df_func = df.apply(func, axis=0)

<class 'pandas.core.series.Series'>
Index(['Dave', 'David'], dtype='object')
[60 70]
<class 'pandas.core.series.Series'>
Index(['Dave', 'David'], dtype='object')
[100  50]

In [27]:
df_func = df.apply(func, axis=1)

<class 'pandas.core.series.Series'>
Index(['영어', '수학'], dtype='object')
[ 60 100]
<class 'pandas.core.series.Series'>
Index(['영어', '수학'], dtype='object')
[70 50]

In [28]:
def func(row) :
    if row["Country_Region"] in json_data :
        row["Country_Region"] = json_data[row["Country_Region"]]
    return row

In [29]:
doc = doc.apply(func, axis=1)
doc.head()

  Province_State Country_Region  Confirmed
0          Anhui          China          1
1        Beijing          China         14
2      Chongqing          China          6
3         Fujian          China          1
5      Guangdong          China         26

In [33]:
data = "01-22-2020.csv"
date_column = data.split(".")[0].lstrip("0").replace("-", "/")
date_column # 1/22/2020

'1/22/2020'

In [35]:
doc.columns = ['Province_State', 'Country_Region', date_column]
doc.columns

Index(['Province_State', 'Country_Region', '1/22/2020'], dtype='object')

In [37]:
doc.head()

  Province_State Country_Region  1/22/2020
0          Anhui          China          1
1        Beijing          China         14
2      Chongqing          China          6
3         Fujian          China          1
5      Guangdong          China         26

In [ ]:
# 1) 원하는 컬럼만 추출 : 해당 원하는 컬럼명 시기에 따라서 달랐기 때문에, try, except 구문 + if
# 2) 각 국가마다 확진자수를 통합 + 각 국가별 공식 명칭에따라 국기를 찾아올 수 있기 때문에 이름 통일 : apply()
# 3) 날짜별 확진자 컬럼 이름을 변경 : split 불필요한 문자열 편집
# 4) 중복 데이터 병합 : groupby

In [40]:
df = pd.DataFrame({
    "성별": ["남", "남", "남"],
    "이름": ["David", "Dave", "Dave"],
    "수학": [100, 50, 50],
    "국어": [80, 70, 50]
})

df

  성별     이름   수학  국어
0  남  David  100  80
1  남   Dave   50  70
2  남   Dave   50  50

In [42]:
selected_columns = ["이름", "수학", "국어"]
df = df[selected_columns]

df.groupby("이름").sum() # groupby 기준값 => 인덱스

        수학   국어
이름
Dave   100  120
David  100   80

In [ ]:
import pandas as pd
import json

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"

with open("./COVID-19-master/csse_covid_19_data/country_convert.json", "r", encoding="utf-8-sig") as json_file :
    json_data = json.load(json_file)

def func(row) :
if row["Country_Region"] in json_data :
    row["Country_Region"] = json_data[row["Country_Region"]]
return row["Country_Region"]

def create_dateframe(filename) :
    doc = pd.read_csv(f"{PATH}{filename}", encoding="utf-8-sig")

try :
    doc = doc[["Province_State", "Country_Region", "Confirmed"]]
except :
    doc = doc[["Province/State", "Country/Region", "Confirmed"]]
    doc.columns = ["Province_State", "Country_Region", "Confirmed"]

doc = doc.dropna(subset=["Confirmed"])
doc["Country_Region"] = doc.apply(country_name_convert, axis=1)
doc = doc.astype({"Confirmed": "int64"})
doc = doc.groupby("Country_Region").sum()

date --

In [ ]:
csv_list

In [ ]:
doc = doc.fillna(0)
doc

In [ ]:
# 다양한 프로그래밍 언어 : 로컬시스템 관련 속성 및 메서드를 사용 -> OS

import os

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
file_list, csv_list = os.listdir(PATH), list()
# csv_list = list()

for file in file_list : 
    if file.split(".") [-1] == "csv" : 
        csv_list.append(file)

print(csv_list)

In [ ]:
from datetime import datetime

# 날짜처럼 생긴 문자 -> 해당 문자를 진짜 날짜로 바꿔줘야 함  -> 가장 오래된 날짜 : 가장 최신 날짜 인식 정렬!
# 람다식 = 메서드 안에 어떤 기능을 구현하ㅏㄹ 수 있는 함수를 또 사용해야하는 경우
# 자바스크립트라는 프로그래망 언어 Javascript => 함수 => 1급 시민
# 함수 안에 함수를 사용 = 콜백
# 함수 안에 return문 안에 함수를 사용
# 함수의 매개별수 = 인자값으로 함수
# 함수의 기능 구현 => 매서드 안에 또 다른 기능구현을 위한 함수를 사용 => 람다식
# 구문 -> 식 : 함수 이름 포기 -> 한줄짜리 식으로 사용!
# 람다식 = 익명함수

csv_list.sort(key = lambda x: datetime.strptime(x, "%m-%d-%Y.csv"))
csv_list