In [ ]:
*** 아나콘다 프로그램 사용 이유!
*저장은 로컬에 진행이 되고 있지만, 실행은 클라우드에서 되어짐
-> 로컬 기반이긴 하나 100%는 아님. (*쨌든? 로컬 프로그램으로 봄)

1. 학습 목적 및 목표 :  파이썬 프로그래밍 언어를 활용해 데이터 수집/분석을 하기 위함
2. 파이썬이라는 프로그래밍 언어는, 다른 언어보다 학습 속도/효과가 빠르기 때문에 배움(난이도 하)
3. 파이썬을 다룰 수 있는 환경을 2가지로 나눠본다면 
- 클라우드(온라인 서버 내 가상 환경) 기반 서비스 ex. 코랩 - 설치가 필요 없으나, 통신의 영향이 多

- 로컬(컴퓨터) 기반 서비스 ex. 아나콘다 - 컴퓨터에 프로그램을 설치하여 안정적으로 파일 관리 
> Web 에디터(ex. VSC) : 주로 프론트엔드(시각적 요소) 개발 시 주 사용 (*내가 작성한 코드가 실시간 웹 구현) 
-> DB, 백엔드 관련 코드 작성하려면 extension이 필수
-> 파이썬의 경우 버전이 정말 다양한데, 각 버전마다 실행이 안 되는 것이 있음 그러면 필요시 매번 가상환경(venv)을 구현해야 함 => 번거로움

> IDE : 통합개발환경
-> 웹 에디터처럼 굳이 프로그래밍 버전 및 운영체제 등의 환경에 따라 별도의 확장 플러그인이나 가상환경을 설치/세팅하지 않아도 됨
-> 즉, 통합개발환경만으로도 모든 것을 구현할 수 있도록 만들어진 프로그램
-> 파이썬 전용 통합개발환경 프로그램으로 가장 적절한 프로그램(무료, 버전관리 및 불필요한 가상환경이 필요 없고, 로컬 설치도 가능)이 아나콘다

*그러면 커서 AI는? 
-> 본인들은 IDE라고 하지만, 사실 설치를 해야 하는 에디터가 맞음. 실제로 설치해야하는 프로그램이 많기 때문

In [ ]:
*** 실무에서 Pandas의 사용목적

1. 테이블형 데이터를 다루는데 있어서 압도적인 기능
2. 원본데이터의 전처리(Preprocessing) 및 정제(Cleannsing) 작업 시, 비교적 간단한 코드만으로 가능
*정제 : 누락된 값(NaN, Null)을 삭제하거나 평균값/최빈값 등으로 대체
*전처리 : 정제 작업을 완료한 후, 데이터를 알고리즘이나 분석 목적에 맞추는 다음 단계들이 포함
3. 데이터 분석 기법을 활용할 때 굉장히 많이 등장함

- EDA : 탐색적 데이터 분석 = Exploratory Data Analysis
> 본격적인 데이터 분석 전 데이터의 사이즈, 결측치, 이상치, 평균 및 중앙값 사분위 데이터 등을 통해서 데이터 패턴을 파악하기 위한 목적을 가지고 있음
    
- LDA : 잠재적 주제도출 분석 = Latent Dirichlet Allocation = 잠재 디리클레 할당
> EDA 과정을 거쳐서 충분히 분석할만한 가치가 있다고 판단은 하였으나, 파편화 되어있는 데이터들이 어떤 주제로 구성되어 있는지를 분류하고 파악하기 위한 목적
> 사용자 및 SNS 키워드 및 리뷰 수집 결과 수가 100만개라고 한다면, 중복되어지는 내용이 많음(나쁘다, 안 좋다, 불편하다) -> 이러한 것을 LDA 과정에서 처리 해야 함

- ETL : 데이터 추출처리 분석 = Extract Transform Load
> 원본 데이터 = 원시데이터는 정보(데이터의 패턴조회, 가설설정)가 아님 -> 원시데이터를 유용한 정보성 요소로 변환시키도록하기 위한 분석 과정

In [ ]:
# pandas는 시리즈와 데이터프레임으로 되어있다.
# 시리즈 : Series() : 1차원 데이터를 말 함(*단일 데이터: 한 줄로 되어 있음) > [] 안에 위치하며, 출력시 데이터 타입이 함께 나옴
# 데이터 프레임 : DataFrame() : 복수의 시리즈가 모여서 만들어진 2차원 데이터(*행/열 테이블 형태) > {} 안에 위치하며, 출력시 기본적으로 인덱스 값이 따라 붙음
# CRUD => SQL => DDL DML, DTL

In [56]:
import pandas as pd

seriesdata = pd.Series([70, 60, 90])
seriesdata = pd.Series([True, False, True])
seriesdata = pd.Series(["A", "B", "C"])

seriesdata

0    A
1    B
2    C
dtype: object

In [16]:
df = pd.DataFrame({
    "미국":  [2.1, 2.2, 2.3],
    "한국":  [0.4, 0.5, 0.45],
    "중국":  [10, 13, 15]
}, index=[2000, 2010, 2020]) #인덱스 표기 따로 안하면 기본 값으로 설정되어서 나옴

df

       미국    한국  중국
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [22]:
df.index #데이터 프레임은, 인덱스/컬럼(열)/로우(행) 이 3가지만 기억해!
df.index = [2001, 2002, 2003]

In [23]:
#값을 가져올 수 있다는 이야기는, 값을 변경할 수 있다는 이야기!

df.colums= ["일본", "필리핀", "러시아"]
df

       미국    한국  중국
2001  2.1  0.40  10
2002  2.2  0.50  13
2003  2.3  0.45  15

In [24]:
df.values

array([[ 2.1 ,  0.4 , 10.  ],
       [ 2.2 ,  0.5 , 13.  ],
       [ 2.3 ,  0.45, 15.  ]])

In [39]:
df = pd.DataFrame({
    "년도":  [2000, 2010, 2020],
    "미국":  [2.1, 2.2, 2.3],
    "한국":  [0.4, 0.5, 0.45],
    "중국":  [10, 13, 15]
})

df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [28]:
#인덱스 값으로 움직이기 
-> 년도를 인덱스 값으로 잡겠다
df = df.set_index("년도")

In [31]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [32]:
#인덱스 값으로 움직이기 
-> 다시 인덱스 값을 살리겠다

df = df.reset_index("년도")

In [34]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [37]:
#인덱스 값으로 움직이기 
#-> 인덱스열 이름을 연도라고 하겠다

df.index.name = "연도"

In [43]:
#컬럼즈, 인덱스

df.iloc[0] #해당 value 값을 인덱스 기반으로 찾아오기

년도    2000.0
미국       2.1
한국       0.4
중국      10.0
Name: 0, dtype: float64

In [44]:
df = df.set_index("년도")

In [46]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [47]:
df.index.name = "연도"

In [49]:
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [54]:
df.iloc[0] #인덱스 기반

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [57]:
df.loc[2000] #인덱스 값기반

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [59]:
#기존에 열만 시리즈 인 줄 알았지? 아니. 행도 시리즈라고 불림

type(df.loc[2000])

pandas.core.series.Series

In [61]:
type(df["미국"])

pandas.core.series.Series

In [62]:
df["미국"][2000] #열 기준으로 행 값 찾아옴

np.float64(2.1)

In [64]:
df.loc[2000]["미국"] #행 기준으로 열 값 찾아옴

np.float64(2.1)

In [ ]:
#위처럼 둘 다 가능한 이유가 바로, 행과 열 모두 시리즈기 때문에 찾아오는 것임

In [65]:
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [66]:
#열 값을 업데이트 하기
df["일본"] = [1,2,3]

In [67]:
df

       미국    한국  중국  일본
연도
2000  2.1  0.40  10   1
2010  2.2  0.50  13   2
2020  2.3  0.45  15   3

In [68]:
#열 값 삭제하기
del df["일본"]

In [69]:
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [ ]:
#행 업데이트

In [70]:
df.loc[2030] = [1,2,3]

In [71]:
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2030  1.0  2.00   3

In [ ]:
#행 삭제

In [73]:
df.drop([2020])

       미국   한국  중국
연도
2000  2.1  0.4  10
2010  2.2  0.5  13
2030  1.0  2.0   3

In [74]:
#복제

#데이터 프레임 재할당 = 별도의 백업파일 생성 X
#데이터 프레임 복제 = 기존 데이터 프레임을 둔 상태로, 새로 데이터 프레임을 생성하는 경우

df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2030  1.0  2.00   3

In [75]:
#복제

df2 = df[["한국", "중국"]].copy()

In [76]:
df2

        한국  중국
연도
2000  0.40  10
2010  0.50  13
2020  0.45  15
2030  2.00   3

In [78]:
#위에서는 복제한 파일이니까 원본 당연히 살아있음
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2030  1.0  2.00   3